# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Find and delete

email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
Hi, this blog is collection of code I find interesting and/or useful.
It is what it lacks in content, organization, and style it makes up for in brevity.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://" # the base hostname & protocol for your site

twitter_username: findanddelete

github_username:  findanddelete

# Build settings
markdown: kramdown
